# Generated by Django 3.0.8 on 2020-07-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sujeto',
            fields=[
                ('id_sujeto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('isPD', models.BooleanField(default=False)),
            ],
        ),
    ]
