# Generated by Django 3.0.8 on 2020-07-29 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0003_auto_20200729_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('is_doctor', 'Is_Doctor'), ('is_administrador', 'Is_administrador'), ('is_cliente', 'Is_Cliente'))},
        ),
    ]
