# Generated by Django 3.0.8 on 2020-08-24 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Overlay', '0003_auto_20200818_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overlay',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='overlay',
            name='tamanio',
        ),
    ]
