# Generated by Django 3.0.8 on 2020-07-29 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sujeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenMRI',
            fields=[
                ('id_mri', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=5)),
                ('tamanio', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=100)),
                ('id_sujeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sujeto.Sujeto')),
            ],
        ),
    ]
