# Generated by Django 3.0.8 on 2020-08-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagenMRI', '0002_imagenmri_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenmri',
            name='descripcion',
            field=models.CharField(default='Ninguna', max_length=150),
        ),
    ]
