# Generated by Django 3.0.8 on 2020-08-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagenMRI', '0004_auto_20200821_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenmri',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='ImagenesMRI/'),
        ),
        migrations.AlterField(
            model_name='imagenmri',
            name='tipo',
            field=models.CharField(choices=[('T', 'T1'), ('F', 'FLAIR')], max_length=1),
        ),
    ]
