# Generated by Django 3.0.8 on 2020-08-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagenMRI', '0005_auto_20200823_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenmri',
            name='tipo',
            field=models.CharField(choices=[('T1', 'T1'), ('FLAIR', 'FLAIR')], max_length=5),
        ),
    ]
