# Generated by Django 3.0.8 on 2020-08-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagenMRI', '0006_auto_20200824_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenmri',
            name='imagen',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='ImagenesMRI/'),
        ),
    ]
