# Generated by Django 3.0.8 on 2020-09-01 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sujeto', '0002_remove_sujeto_ispd'),
        ('ImagenMRI', '0007_auto_20200825_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenmri',
            name='id_sujeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sujeto.Sujeto'),
        ),
        migrations.AlterField(
            model_name='imagenmri',
            name='imagen',
            field=models.FileField(max_length=1000, upload_to='ImagenesMRI/'),
        ),
    ]
