# Generated by Django 3.0.8 on 2020-07-29 23:51

import apps.Usuario.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuario', '0004_auto_20200729_1830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telefono', models.CharField(max_length=20)),
                ('cedula', models.CharField(max_length=10, null=True, unique=True)),
            ],
            options={
                'db_table': 'Doctor',
            },
            bases=('Usuario.usuario',),
            managers=[
                ('objects', apps.Usuario.models.PersonalizadaBaseUserManager()),
            ],
        ),
    ]
