# Generated by Django 3.0.8 on 2020-08-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSV',
            fields=[
                ('id_csv', models.AutoField(primary_key=True, serialize=False)),
                ('documento', models.FileField(blank=True, null=True, upload_to='DATASET_HABLA/')),
                ('titulo', models.CharField(max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=200, null=True)),
            ],
            options={
                'ordering': ['id_csv'],
            },
        ),
    ]
