# Generated by Django 3.0.8 on 2020-09-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Archivo', '0002_auto_20200903_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='descripcion',
            field=models.CharField(default='--', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='csv',
            name='titulo',
            field=models.CharField(default='--', max_length=20, null=True),
        ),
    ]
