# Generated by Django 3.0.8 on 2020-08-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImagenMascara', '0003_imagenmascara_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenmascara',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='imagenmascara',
            name='tamanio',
        ),
    ]
