# Generated by Django 3.0.8 on 2020-08-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImagenMascara', '0004_auto_20200824_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenmascara',
            name='descripcion',
        ),
    ]
