# Generated by Django 3.0.8 on 2020-08-25 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagenMascara', '0005_remove_imagenmascara_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenmascara',
            name='id_mri',
        ),
        migrations.AlterField(
            model_name='imagenmascara',
            name='imagen',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='ImagenesMascaras/'),
        ),
    ]
