# Generated by Django 3.0.8 on 2020-07-29 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ImagenMascara', '0001_initial'),
        ('Sujeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaCaracteristicas',
            fields=[
                ('id_tablaC', models.AutoField(primary_key=True, serialize=False)),
                ('nombrePaciente', models.CharField(max_length=30)),
                ('curtosisI', models.DecimalField(decimal_places=7, max_digits=9)),
                ('areaI', models.DecimalField(decimal_places=7, max_digits=9)),
                ('redondezI', models.DecimalField(decimal_places=7, max_digits=9)),
                ('perimetroI', models.DecimalField(decimal_places=7, max_digits=9)),
                ('varianzaI', models.DecimalField(decimal_places=7, max_digits=9)),
                ('desviEstandI', models.DecimalField(decimal_places=7, max_digits=9)),
                ('enlogacionF', models.DecimalField(decimal_places=7, max_digits=9)),
                ('flagnessF', models.DecimalField(decimal_places=7, max_digits=9)),
                ('volumenF', models.DecimalField(decimal_places=7, max_digits=9)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('id_mask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ImagenMascara.ImagenMascara')),
                ('id_sujeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sujeto.Sujeto')),
            ],
        ),
    ]
