# Generated by Django 3.0.8 on 2020-08-18 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='descripcion',
            field=models.CharField(default='Ninguna', max_length=150),
        ),
    ]
