# Generated by Django 3.0.8 on 2020-08-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostico', '0002_diagnostico_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='porcentNoPD',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='porcentPD',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3, null=True),
        ),
    ]
