# Generated by Django 3.0.8 on 2020-08-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostico', '0003_auto_20200825_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='porcentNoPD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='porcentPD',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
