# Generated by Django 3.0.8 on 2020-09-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostico', '0005_auto_20200825_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='is_parkinson',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
