# Generated by Django 3.0.8 on 2020-09-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diagnostico', '0005_auto_20200825_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='descripcion',
            field=models.CharField(default='Ninguna', max_length=350),
        ),
    ]
